version: 1
formatters:
  basic:
    format: "[%(asctime)s][%(levelname)s] %(name)s:L%(lineno)d %(message)s"
  message:
    formate: "%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: message
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: basic
    filename: log.txt
    encoding: UTF-8-sig
    maxBytes: 102400
    backupCount: 1
root:
  level: DEBUG
  handlers:
    - file_handler
